import json as json

#json_str = '{"restart_counter" : 13, "version_major" : 1, "version_minor" : 1, "build" : "20121116-210859", "sensors" : [ {"id" : 0, "name" : "STROM                  ", "enabled" : 1, "type" : "EHZ", "address" : 0, "value" : 95645104, "value2" : 1764},{"id" : 1, "name" : "WASSER        [10L/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 33164, "value2" : 0},{"id" : 2, "name" : "GAS       [0.01m^3/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 378180, "value2" : 0},{"id" : 3, "name" : "WASSER GARTEN  [1L/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 0, "value2" : 0},{"id" : 4, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 5, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 6, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 7, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0} ] }'
#json_str = '{"restart_counter" : 13, "version_major" : 1, "version_minor" : 2, "sensors" : [ {"id" : 0, "enabled" : 1, "type" : "EHZ", "address" : 0, "value" : 84784693, "value2" : 0},{"id" : 1, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 2, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 3, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 4, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 5, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 6, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 7, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0} ] }'
#json_str = '{"restart_counter" : 13, "version_major" : 1, "version_minor" : 1, "build" : "20121111-221516", "sensors" : [ {"id" : 0, "name" : "STROM" , "enabled" : 1, "type" : "EHZ", "address" : 0, "value" : 94652504, "value2" : 2602},{"id" : 1, "name" : "WASSER [10L/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 32862, "value2" : 0},{"id" : 2, "name" : "GAS [0,01m^3/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 373014, "value2" : 0},{"id" : 3, "name" : "WASSER GARTEN [1L/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 0, "value2" : 0},{"id" : 4, name : -, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 5, name : -, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 6, name : -, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 7, name : -, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0} ] }'
json_str =  '{"restart_counter" : 13, "version_major" : 1, "version_minor" : 1, "build" : "20121111-221516", "sensors" : [ {"id" : 0, "name" : "STROM                  ", "enabled" : 1, "type" : "EHZ", "address" : 0, "value" : 94682543, "value2" : 3775},{"id" : 1, "name" : "WASSER        [10L/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 32867, "value2" : 0},{"id" : 2, "name" : "GAS       [0,01m^3/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 373262, "value2" : 0},{"id" : 3, "name" : "WASSER GARTEN  [1L/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 0, "value2" : 0},{"id" : 4, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 5, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 6, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 7, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0} ] }'
#{"restart_counter" : 13, "version_major" : 1, "version_minor" : 1, "build" : 20121111-221516, "sensors" : [ {"id" : 0, name : STROM , "enabled" : 1, "type" : "EHZ", "address" : 0, "value" : 94652504, "value2" : 2602},{"id" : 1, name : WASSER [10L/Imp], "enabled" : 1, "type" : "S0", "address" : 0, "value" : 32862, "value2" : 0},{"id" : 2, name : GAS [0,01m^3/Imp], "enabled" : 1, "type" : "S0", "address" : 0, "value" : 373014, "value2" : 0},{"id" : 3, name : WASSER GARTEN [1L/Imp], "enabled" : 1, "type" : "S0", "address" : 0, "value" : 0, "value2" : 0},{"id" : 4, name : -, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 5, name : -, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 6, name : -, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 7, name : -, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0} ] }'
#json_str = '{"restart_counter" : 13, "version_major" : 1, "version_minor" : 1, "sensors" : [ {"id" : 0, "name" : "STROM                  ", "enabled" : 1, "type" : "EHZ", "address" : 0, "value" : 95645104, "value2" : 1764},{"id" : 1, "name" : "WASSER        [10L/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 33164, "value2" : 0},{"id" : 2, "name" : "GAS       [0.01m^3/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 378180, "value2" : 0},{"id" : 3, "name" : "WASSER GARTEN  [1L/Imp]", "enabled" : 1, "type" : "S0", "address" : 0, "value" : 0, "value2" : 0},{"id" : 4, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 5, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 6, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 7, "name" : "-", "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0} ] }'
#json_str = '{"restart_counter" : 13, "version_major" : 1, "version_minor" : 2, "sensors" : [ {"id" : 0,                                     "enabled" : 1, "type" : "EHZ", "address" : 0, "value" : 84784693, "value2" :    0},{"id" : 1,                                     "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 2, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 3, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 4, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 5, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 6, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0},{"id" : 7, "enabled" : 0, "type" : "NONE", "address" : 0, "value" : 0, "value2" : 0} ] }'


data = json.loads(json_str)
print len(data['sensors'])
#print data['build']
print data['sensors'][1]['value']
